### ISSUE TITLE
PG::Numeric converter

### ISSUE THREAD

**Issue by Blacksmoke16** [vladfaust/core#104]
Currently when using a float column type other than REAL/DOUBLE PRECISION, it will throw a `PG::ResultSet#read returned a PG::Numeric. A (Float64 | Nil) was expected`

```cr
  class Character
    include Onyx::SQL::Model

    schema characters do
      pkey id : Int32
      type balance : Float64, not_null: true # => DECIMAL(16, 2)
    end
  end
```

Prob just need to add a converter to convert `PG::Numeric` type into the desired numeric type.

**Comment by vladfaust** [comment]
You could either use `FLOAT8` type in PG or use `PG::Numeric` converter (if it doesn't work out of the box, try creating one, looking at [PG::Enum](https://github.com/onyxframework/sql/blob/master/src/onyx-sql/converters/pg/enum.cr) for inspiration.

**Comment by Blacksmoke16** [comment]
I was originally using FLOAT8, but need DECIMAL for the precision.  But yea, I ended up just defining my own converter.  Is that something you would want built in tho?

**Comment by vladfaust** [comment]
I think that it wouldn't be bad to have such a converter by default...
