### ISSUE TITLE
Transactions

### ISSUE THREAD

**Issue by greenbigfrog** [vladfaust/core#30]
Not sure if I'm missing it, or if core.cr doesn't support transactions.

**Comment by vladfaust** [comment]
Hello, @greenbigfrog,

I **suppose** that should do the case:

```crystal
db = DB.open(ENV["DATABASE_URL"])
db.transaction do |tx|
  repo = Core::Repository.new(tx.connection, query_logger)
  repo.insert(something)
  repo.query(something)
end
```

You can read more about transactions [here](http://crystal-lang.github.io/crystal-db/api/0.4.2/DB/Transaction.html) (though it's terribly documented). A working example of Crystal DB transaction could be found [here](https://github.com/vladfaust/migrate.cr/blob/master/src/migrate/migrator.cr#L124).

Do not hesitate asking more questions or suggesting better implementation!

**Comment by greenbigfrog** [comment]
Thanks. That should do the job! For now I'll try to go plain SQL... Never a bad idea to know how to do it without help...

**Comment by greenbigfrog** [comment]
Since you seam to know your way around transactions I've still got a question for you. How can I send different log messages, depending on if a transaction was successfull or not?

```crystal
db.transaction do |tx|
  tx.exec(sth)
end
# if successfull log `tada` else log `error`
```

**Comment by vladfaust** [comment]
@greenbigfrog see [this](http://crystal-lang.github.io/crystal-db/api/0.4.2/DB/BeginTransaction.html#transaction%28%26block%29-instance-method), whatever it means 😅 

In a nutshell - `begin` 'n `rescue` are youre friends here...

**Comment by greenbigfrog** [comment]
Hm. I guess I'll just have to do some testing... Thanks

**Comment by vladfaust** [comment]
@greenbigfrog please share your thoughts after testing!
