### ISSUE TITLE
Add .[] to Schema

### ISSUE THREAD

**Issue by vladfaust** [vladfaust/core#64]
```crystal
User[42] == Query(User).new.where(id: 42)
```

**Comment by vladfaust** [comment]
Not sure if it's needed.

**Comment by Jens0512** [comment]
*Looks* great IMO. I have to say, this ORM looks amazing, really looking forward to seeing it maturing!

**Comment by vladfaust** [comment]
@Jens0512 thanks for your kind words! Check out the fresh new release :rocket:
