### ISSUE TITLE
`schema "table" do`

### ISSUE THREAD

**Issue by vladfaust** [vladfaust/core#7]
Table name is essential, so make it [#schema](https://vladfaust.com/core.cr/Core/Model/Schema.html#schema-macro)'s argument *just like Crecto*? :thinking:

**Comment by Brusalk** [comment]
I like the self-documenting nature of https://vladfaust.com/core.cr/Core/Model/Schema.html#table_name%28name%29-macro personally.

**Comment by vladfaust** [comment]
@Brusalk a newcomer may not notice `table_name` macro and currently there is no any error message stating that it's missed. I should either check it upon `#schema` execution finale or add an argument, which feels more native.
