### ISSUE TITLE
BigRational

### ISSUE THREAD

**Issue by jackturnbull** [vladfaust/core#8]
Thanks for the lib! I'm finding the more lightweight approach to be easier to wrap my head around than Crecto, but I am struggling with something as it stands (sorry I'm a typed languages noob - it could be simple)

I want to use `BigRational` to be able to represent financial data but my initial attempts have been thwarted. A bit of trial and error has helped but still banging my head against the wall.

I'm hoping to take advantage of [the PG::Numeric extensions](https://github.com/crystal-lang/crystal/blob/3c712288ba8f8138cb734e673cc622658300c229/src/big/big_rational.cr) to pull data in and out of a Postgres `DECIMAL(20,8)`

Initial attempt was to:

```crystal
require "big_rational"

module Models
  class Order < Core::Model
    schema do
      primary_key :id
      field :rate, BigRational
      field :quantity, BigRational
    end
  end
end
```
```
> instance variable '@changes' of Models::Order must be Hash(Symbol, Number), not (Hash(Symbol, BigRational | Int32) | Hash(Symbol, Number))
```

Which I didn't expect to be a problem since I thought BigRational _was_ a Number

I've also tried to define my own converter, but I'm not confident in what I should be converting to/from, being honest!

**Comment by vladfaust** [comment]
@jackturnbull have you tried [PG::Numeric](https://github.com/will/crystal-pg/blob/master/src/pg/numeric.cr)?

**Comment by jackturnbull** [comment]
I have and that's where I got stuck trying to write the converter. In particular from_json. Although doable, figuring out a solid conversion between an existing number and the `@ndigits, @weight, sign, @dscale, @digits` parameters seemed like way more work than representing it as a Float64 and [converting to a BigR](https://github.com/crystal-lang/crystal/blob/master/src/big/big_rational.cr#L47) before running calculations

Slight disclaimer that I haven't actually worked through this and I'm working on the assumption that Float64 offers me enough precision _prior_ to any calculations

**Comment by vladfaust** [comment]
@jackturnbull you may close the issue if 3024d49dd29116c7416377b22f179b3ccc0618d8 seems enough for your needs.

**Comment by jackturnbull** [comment]
Just had time to have a look through this and get my head around the internals of it. I didn't think it was required at first but that was just because I was using the models in memory.

For my money, I'm happy with this! I can new up a BigR from an Float64 when I need to do any mathematics. Ideally PG::Numeric would have a more friendly initializer but such is life.

Thanks for the update!
