### ISSUE TITLE
Recommended way to convert complex types

### ISSUE THREAD

**Issue by docsncode** [vladfaust/core#9]
Is this the recommended way to covert from JSON for a complex type like PG::Geo::Point?

```crystal
struct PointConverter
  def self.from_rs(rs)
    rs.read(PG::Geo::Point)
  end

  def self.to_json(value, json)
    json.object do
      json.field "x", value.x
      json.field "y", value.y
    end
  end

  def self.from_json(pull)
    pull.read_next
    pull.read_next
    # not checking order of keys
    x = pull.read_float.to_f64
    pull.read_next
    y = pull.read_float.to_f64
    PG::Geo::Point.new(x, y)
  end
end

class Place < Core::Model
  schema do
    table_name "places"

    primary_key :id
    field :name, String
    field :location, PG::Geo::Point, converter: PointConverter
    created_at_field :created_at

    reference :referrer, Place, key: :referrer_id, foreign_key: :id
  end
end

place = Place.from_json "{...}"
```

Using`JSON.mapping` (and not Core) to decode from JSON looks like this:

```crystal
class Point
  JSON.mapping({
    x: Float64,
    y: Float64,
  })
end

class Place
  JSON.mapping({
    id:         Int32,
    name:       String,
    location:   Point,
    created_at: Time,
  })
end

place = Place.from_json "{...}"
```

With Core is there a way to specify a class with a JSON.mapping instead of having to define a convertor with `from_json` and work with the PullParser?

**Comment by vladfaust** [comment]
@SeanPackham, hi there,

I honestly hadn't have any experience with complex types yet. Still, AFAIK, `.from_json` (as well as `.to_json` and `.from_rs`) applies to all underlying objects too, therefore it should definitely be possible to define a model field of type `Point`.

Please check upcoming [v0.3.0 release](https://github.com/vladfaust/core.cr/releases/tag/v0.3.0), where JSON and DB converters are split.

**Comment by docsncode** [comment]
I tool a look at v0.3.0 and you also have to define a `from_json` method even if the complex type has a `JSON.mapping`. I will keep experimenting :) Thanks for the reply!
